### ISSUE TITLE
ROS topic names ignore namespace configuration when spawning multiple robots of the same model

### ISSUE THREAD

**Issue by nahueespinosa** [avidbots/flatland#89]
Hi! There seems to be a bug in the way ROS topic names are loaded in various plugins.

### How to reproduce
Add a laser plugin to a robot model:
```yaml
plugins:
  - type: Laser
    name: laser_front
    frame: laser_front
    topic: scan2
    body: base2
    broadcast_tf: true
    origin: [0.28, 0, 0]
    range: 20
    angle: {min: -2.356194490192345, max: 2.356194490192345, increment: 0.004363323129985824}
    noise_std_dev: 0.05
    update_rate: 40
```

Launch a `flatland_server` node with the following world configuration file and see how both robots publish on the same topic (`/scan2`):
```yaml
models:
  - name: turtlebot1
    namespace: robot1
    pose: [0, 0, 0]
    model: "turtlebot.model.yaml"
    
  - name: turtlebot2
    namespace: robot2
    pose: [0, 1, 0]
    model: "turtlebot.model.yaml"
```

### Cause
In `flatland_server/src/model.cpp` there is a function called [`NameSpaceTopic`](https://github.com/avidbots/flatland/blob/4deeb97c4756e84c4202fec0b078e937f66e3504/flatland_server/src/model.cpp#L194) used to prepend the namespace to the topic name before creating a publisher.

Currently, this is only used in [`bool_sensor.cpp`](https://github.com/avidbots/flatland/blob/4deeb97c4756e84c4202fec0b078e937f66e3504/flatland_plugins/src/bool_sensor.cpp#L85) but it should probably be added to other plugins, like [`laser.cpp`](https://github.com/avidbots/flatland/blob/4deeb97c4756e84c4202fec0b078e937f66e3504/flatland_plugins/src/laser.cpp#L66).
